[package]
name = "memory"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "memory_01"
path = "./src/memory_01.rs"

[[bin]]
name = "memory_02"
path = "./src/memory_02.rs"